on:
  pull_request:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Typstyle
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: typstyle
      - name: Format typst files
        run: typstyle format-all
      - uses: rmburg/action-git-diff-suggestions@main
        with:
          message: "Typstyle suggested the following changes:"
